Update to MP6 and JEE10
OpenLiberty/draft-guide-okd-crc pull request #48
Opened 2023-05-03 21:38 UTC by gkwan-ibm

address issue: https://github.com/OpenLiberty/guides-common/issues/891

### Review changes
- [ ]  pom.xml
  - java 11
  - jakarta is 10, microfile-profile is 6.0, and dependencies
  - LMP 3.7.1
- [ ] server.xml
  - features version
- [ ] index.html
  - license and features version
- [ ] java files
  - EPL 2.0
- [ ] License file
   - EPL 2.0

### End-to-end test
- [ ] update lgdev with `version-update-mp6` branch
- [ ] do end-to-end test and review content carefully
  - clone the `version-update-mp6` branch
  - if index.html has changes, make sure the links work

### Cloud hosted test
- [ ] generate the cloud hosted dev lab
- [ ] do end-to-end test and review content
  - clone the `version-update-mp6` branch

2023-07-07 15:58 UTC, saumyapandyaa approved these changes, later dismissed

2023-08-04 17:03 UTC, saumyapandyaa commented
tested end-to-end on mac and RHEL with no issues

2023-08-04 18:25 UTC, saumyapandyaa approved these changes

2023-08-07 15:28 UTC, dmuelle requested changes
ID review

2023-08-07 15:28 UTC, dmuelle commented on README.adoc
> +Before you begin, the following tool needs to be installed:
```suggestion
Before you begin, install OpenShift Local.
```

2023-08-07 15:28 UTC, dmuelle commented on README.adoc
> +* *OpenShift Local:* You need to install OpenShift Local to run OpenShift 4 locally on your computer. For installation instructions, refer to the official https://access.redhat.com/documentation/en-u
```suggestion
You must install OpenShift Local to run OpenShift 4 locally on your computer. For installation instructions, refer to the official https://access.redhat.com/documentation/en-us/red_hat_openshift_local/2.23/html/getting_started_guide/installing[OpenShift Local documentation].   
```

2023-08-07 15:28 UTC, dmuelle commented on README.adoc
> +When prompted, supply your user pull secret. The pull secret can be found on the page where you downloaded the https://cloud.redhat.com/openshift/create/local[latest release of OpenShift Local].
```suggestion
Supply your user pull secret at the prompt. You can find the pull secret  on the page where you downloaded the https://cloud.redhat.com/openshift/create/local[latest release of OpenShift Local].
```

2023-08-07 15:28 UTC, dmuelle commented on README.adoc
>  The resulting output differs based on your OS and environment, but you should get an output similar to the following:
```suggestion
The resulting output differs based on your OS and environment, but the output is similar to the following example:
```

2023-08-07 15:28 UTC, dmuelle commented on README.adoc
> +You just deployed two microservices running in Open Liberty to OpenShift cluster using OpenShift Local. You also learned how to use `oc` to deploy your microservices on a {kube} cluster.
```suggestion
You just deployed two microservices running in Open Liberty to an OpenShift cluster by using OpenShift Local. You also learned how to use `oc` to deploy your microservices on a {kube} cluster.
```

2023-08-10 14:58 UTC, dmuelle requested changes
LGTM except for a minor edit to the display title

2023-08-10 14:58 UTC, dmuelle commented on README.adoc
> += Deploying microservices to OpenShift cluster using OpenShift Local
```suggestion
= Deploying microservices to an OpenShift cluster using OpenShift Local
```

2023-08-10 16:50 UTC, dmuelle approved these changes
LGTM, thanks

2023-08-10 18:36 UTC, merged